# 1. Запрашиваем свежий релиз
- name: Query Checkpoint API
  uri:
    url: https://checkpoint-api.hashicorp.com/v1/check/terraform
    return_content: yes
  register: checkpoint
  retries: 4
  delay: 3
  until: checkpoint is succeeded
  changed_when: false

- set_fact:
    terraform_latest: "{{ checkpoint.json.current_version }}"

# 2. Проверяем, установлен ли terraform (без JSON‑парсинга, чтобы не падать)
- name: Is terraform binary in PATH?
  shell: command -v terraform
  register: tf_bin
  changed_when: false
  failed_when: false

# 3. Если бинарь найден — получаем версию, иначе помечаем как 'none'
- name: Get installed version (if any)
  shell: terraform version -json
  when: tf_bin.rc == 0
  register: tf_version
  changed_when: false
  failed_when: false

- set_fact:
    terraform_installed: >-
      {{ (tf_version.stdout | from_json).terraform_version
         if tf_bin.rc == 0 else 'none' }}

# 4. Решаем, что делать
- set_fact:
    terraform_action: >-
      {% if terraform_installed == 'none' %}
        install
      {% elif terraform_latest is version_compare(terraform_installed, '>', strict=True') %}
        update
      {% else %}
        skip
      {% endif %}
  changed_when: false

# 5. Показываем, что получилось (для вашей проверки)
- debug:
    msg: |
      Latest: {{ terraform_latest }}
      Installed (none если нет): {{ terraform_installed }}
      Action: {{ terraform_action }}
  changed_when: false
