---
- name: Install prerequisites (Debian family)
  apt:
    name:
      - gnupg
      - software-properties-common
      - unzip
      - curl
    state: present
    update_cache: yes

- name: Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repository
  apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Install specific Terraform version
  apt:
    name: "terraform={{ terraform_version }}"
    state: present
  register: tf_install

- name: Verify installation
  command: terraform --version
  changed_when: false
