---
# roles/terraform/tasks/install_fedora.yml
# Fedora‑only installer that mirrors:
#   1) sudo dnf install -y dnf-plugins-core
#   2) sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
#   3) sudo dnf install -y terraform

- name: Ensure dnf-plugins-core is present
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
    update_cache: yes

- name: Add HashiCorp repo via config‑manager (idempotent)
  ansible.builtin.command:
    cmd: >
      dnf config-manager --add-repo
      https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
  args:
    # создаст файл /etc/yum.repos.d/hashicorp.repo, поэтому второй запуск пропускается
    creates: /etc/yum.repos.d/hashicorp.repo
  register: add_repo
  changed_when: add_repo.rc == 0

- name: Install / upgrade Terraform
  ansible.builtin.dnf:
    name: terraform
    state: "{{ terraform_state | default('latest') }}"
    update_cache: yes
