# Install specific Terraform version on RedHat‑like OS
- name: Ensure prerequisites are present
  dnf:
    name:
      - yum-utils
      - curl
      - unzip
    state: present
  become: true

- name: Add HashiCorp repo
  get_url:
    url: https://rpm.releases.hashicorp.com/rpm/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
  become: true

- name: Install Terraform {{ terraform_latest }}
  dnf:
    name: "terraform-{{ terraform_latest }}"
    state: present # first install
  become: true
