---
- name: Install prerequisites (RedHat family)
  dnf:
    name:
      - yum-utils
      - unzip
      - curl
    state: present

- name: Add HashiCorp repo
  get_url:
    url: https://rpm.releases.hashicorp.com/rpm/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install specific Terraform version
  dnf:
    name: "terraform-{{ terraform_version }}"
    state: present
  register: tf_install

- name: Verify installation
  command: terraform --version
  changed_when: false
